# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: urun.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'urun.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nurun.proto\">\n\x0eUrunEkleIstegi\x12\n\n\x02\x61\x64\x18\x01 \x01(\t\x12\r\n\x05\x66iyat\x18\x02 \x01(\x02\x12\x11\n\tstokta_mi\x18\x03 \x01(\x08\"U\n\nUrunYaniti\x12\n\n\x02id\x18\x01 \x01(\x05\x12\n\n\x02\x61\x64\x18\x02 \x01(\t\x12\r\n\x05\x66iyat\x18\x03 \x01(\x02\x12\x11\n\tstokta_mi\x18\x04 \x01(\x08\x12\r\n\x05mesaj\x18\x05 \x01(\t\"\n\n\x08\x42osIstek\"1\n\x11UrunListesiYaniti\x12\x1c\n\x07urunler\x18\x01 \x03(\x0b\x32\x0b.UrunYaniti2m\n\x0bUrunServisi\x12*\n\x08UrunEkle\x12\x0f.UrunEkleIstegi\x1a\x0b.UrunYaniti\"\x00\x12\x32\n\x0fUrunleriListele\x12\t.BosIstek\x1a\x12.UrunListesiYaniti\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'urun_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_URUNEKLEISTEGI']._serialized_start=14
  _globals['_URUNEKLEISTEGI']._serialized_end=76
  _globals['_URUNYANITI']._serialized_start=78
  _globals['_URUNYANITI']._serialized_end=163
  _globals['_BOSISTEK']._serialized_start=165
  _globals['_BOSISTEK']._serialized_end=175
  _globals['_URUNLISTESIYANITI']._serialized_start=177
  _globals['_URUNLISTESIYANITI']._serialized_end=226
  _globals['_URUNSERVISI']._serialized_start=228
  _globals['_URUNSERVISI']._serialized_end=337
# @@protoc_insertion_point(module_scope)
