# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import urun_pb2 as urun__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in urun_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UrunServisiStub(object):
    """Servis Tanımı (Fonksiyonlar)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UrunEkle = channel.unary_unary(
                '/UrunServisi/UrunEkle',
                request_serializer=urun__pb2.UrunEkleIstegi.SerializeToString,
                response_deserializer=urun__pb2.UrunYaniti.FromString,
                _registered_method=True)
        self.UrunleriListele = channel.unary_unary(
                '/UrunServisi/UrunleriListele',
                request_serializer=urun__pb2.BosIstek.SerializeToString,
                response_deserializer=urun__pb2.UrunListesiYaniti.FromString,
                _registered_method=True)


class UrunServisiServicer(object):
    """Servis Tanımı (Fonksiyonlar)
    """

    def UrunEkle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UrunleriListele(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UrunServisiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UrunEkle': grpc.unary_unary_rpc_method_handler(
                    servicer.UrunEkle,
                    request_deserializer=urun__pb2.UrunEkleIstegi.FromString,
                    response_serializer=urun__pb2.UrunYaniti.SerializeToString,
            ),
            'UrunleriListele': grpc.unary_unary_rpc_method_handler(
                    servicer.UrunleriListele,
                    request_deserializer=urun__pb2.BosIstek.FromString,
                    response_serializer=urun__pb2.UrunListesiYaniti.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UrunServisi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('UrunServisi', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UrunServisi(object):
    """Servis Tanımı (Fonksiyonlar)
    """

    @staticmethod
    def UrunEkle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UrunServisi/UrunEkle',
            urun__pb2.UrunEkleIstegi.SerializeToString,
            urun__pb2.UrunYaniti.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UrunleriListele(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UrunServisi/UrunleriListele',
            urun__pb2.BosIstek.SerializeToString,
            urun__pb2.UrunListesiYaniti.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
